/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Controller;
import domain.Guest;
import domain.Reservation;
import domain.Room;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.DefaultListModel;
import javax.swing.JLayeredPane;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Peter
 */
public class CasablancaResception extends javax.swing.JFrame
{

    private Controller control;
    private int numOfGuest;
    private DefaultListModel model, showOpenReservation, overDueDeposit;
    private String type;
    private int[] priceList;
    private int priceType;
    private boolean visible = true;
    private Date startDate, endDate, bookingDate, date, today;
    private String endDateStr, startDateStr;
    private int totalPriceForRoom;
    private int depositPaid;
    private int roomNo, reservationNo;
    private JLayeredPane currentPane;
    private int guestcounter = 0;

    /**
     * Creates new form CasablancaResception
     */
    public CasablancaResception()
    {
        Calendar c = Calendar.getInstance();
        today = c.getTime();

        initComponents();
        jLayeredPaneReservation.setVisible(false);
        jLayeredPaneReservationInfo.setVisible(false);
        jLayeredPaneSearchGuest.setVisible(false);
        jLayeredPaneEnterGuestInfo.setVisible(false);
        jLayeredPaneShowOpenReservations.setVisible(false);
        control = new Controller();
        model = new DefaultListModel();
        showOpenReservation = new DefaultListModel();
        overDueDeposit = new DefaultListModel();
        model.addElement("Please insert information above");
        jList1.setModel(model);
        priceList = new int[3];
        priceList = control.getPriceList();
        priceType = priceList[0];
        jLabelShowPrice.setText(Integer.toString(priceType));
        currentPane = jLayeredPaneSearchRoome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLayeredPaneSearchRoome = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextFieldNumberOfDays = new javax.swing.JTextField();
        jLabelEndDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelType = new javax.swing.JLabel();
        jLabelTypeShow = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelShowTotalPrice = new javax.swing.JLabel();
        jLabelShowPrice = new javax.swing.JLabel();
        jTextFieldStartDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabelShowRoomChosen = new javax.swing.JLabel();
        jButtonPrintDate = new javax.swing.JButton();
        jLayeredPaneReservation = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelSelectedStartDate = new javax.swing.JLabel();
        jLabelToDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelNumOfGuestReser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelShowType = new javax.swing.JLabel();
        jLabelPriceReservation = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabelReservationNo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLayeredPaneReservationInfo = new javax.swing.JLayeredPane();
        jButtonSeachReservationNo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldReservationInfoSearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextAreaReservationInfo = new javax.swing.JTextArea();
        jLayeredPaneSearchGuest = new javax.swing.JLayeredPane();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLayeredPaneEnterGuestInfo = new javax.swing.JLayeredPane();
        fName = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        phoneNo = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        trvlAgncy = new javax.swing.JLabel();
        checkin = new javax.swing.JLabel();
        noOfnights = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        fNamePANE = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        lNamePANE = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        AddressPANE = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        countryPANE = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        phoneNoPANE = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        emailPANE = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        trvlAgncyPANE = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        checkinPANE = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        noOfnightsPANE = new javax.swing.JTextPane();
        guestInfoSaveButton = new javax.swing.JButton();
        jLayeredPaneShowOpenReservations = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListOverDue = new javax.swing.JList();
        jButtonFindOpenReservations = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        jListOpen = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(null);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jLayeredPaneSearchRoome.setAutoscrolls(true);
        jLayeredPaneSearchRoome.setMaximumSize(new java.awt.Dimension(625, 380));
        jLayeredPaneSearchRoome.setMinimumSize(new java.awt.Dimension(625, 380));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Rooms"));
        jPanel1.setMinimumSize(new java.awt.Dimension(435, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(435, 250));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldNumberOfDays.setToolTipText("");
        jTextFieldNumberOfDays.setMinimumSize(new java.awt.Dimension(27, 20));
        jTextFieldNumberOfDays.setPreferredSize(new java.awt.Dimension(27, 20));
        jTextFieldNumberOfDays.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldNumberOfDaysActionPerformed(evt);
            }
        });

        jLabelEndDate.setMinimumSize(new java.awt.Dimension(10, 15));
        jLabelEndDate.setPreferredSize(new java.awt.Dimension(10, 15));

        jLabel3.setText("Start Date");
        jLabel3.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 25));

        jLabel4.setText("Number of Nights");

        jLabel5.setText("End date");

        jTextField1.setMaximumSize(new java.awt.Dimension(500, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(27, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(27, 20));

        jLabel2.setText("Number of guest");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelType.setText("Type");
        jLabelType.setMinimumSize(new java.awt.Dimension(65, 16));
        jLabelType.setPreferredSize(new java.awt.Dimension(65, 16));

        jLabelTypeShow.setMaximumSize(new java.awt.Dimension(90, 16));
        jLabelTypeShow.setMinimumSize(new java.awt.Dimension(90, 16));
        jLabelTypeShow.setPreferredSize(new java.awt.Dimension(90, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTypeShow, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTypeShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Family" }));
        jComboBoxType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Price");

        jLabelShowTotalPrice.setMaximumSize(new java.awt.Dimension(51, 16));
        jLabelShowTotalPrice.setMinimumSize(new java.awt.Dimension(51, 16));
        jLabelShowTotalPrice.setPreferredSize(new java.awt.Dimension(51, 16));

        jTextFieldStartDate.setDateFormatString("dd-MM-yy");
        jTextFieldStartDate.setMinSelectableDate(today);
        jTextFieldStartDate.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTextFieldStartDateFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldNumberOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelShowTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelShowTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabelEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNumberOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelShowRoomChosen.setText("jLabel6");

        jButtonPrintDate.setText("Print date");
        jButtonPrintDate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonPrintDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPaneSearchRoomeLayout = new javax.swing.GroupLayout(jLayeredPaneSearchRoome);
        jLayeredPaneSearchRoome.setLayout(jLayeredPaneSearchRoomeLayout);
        jLayeredPaneSearchRoomeLayout.setHorizontalGroup(
            jLayeredPaneSearchRoomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSearchRoomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneSearchRoomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPaneSearchRoomeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPaneSearchRoomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabelShowRoomChosen)))
                    .addGroup(jLayeredPaneSearchRoomeLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButtonPrintDate)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneSearchRoomeLayout.setVerticalGroup(
            jLayeredPaneSearchRoomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSearchRoomeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneSearchRoomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPaneSearchRoomeLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelShowRoomChosen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrintDate)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jLayeredPaneSearchRoome.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSearchRoome.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSearchRoome.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSearchRoome.setLayer(jLabelShowRoomChosen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSearchRoome.setLayer(jButtonPrintDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPaneReservation.setMinimumSize(new java.awt.Dimension(625, 380));

        jLabel6.setText("From");

        jLabelSelectedStartDate.setText("jLabel6");

        jLabelToDate.setText("jLabel8");

        jLabel7.setText("To");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSelectedStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectedStartDate)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelToDate))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabelNumOfGuestReser.setText("jLabel8");

        jLabel8.setText("Num. Of Guest");

        jLabel9.setText("Type");

        jLabelShowType.setText("jLabel10");

        jLabelPriceReservation.setText("jLabel10");

        jCheckBox1.setText("Paid Deposit");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelShowType)
                            .addComponent(jLabelNumOfGuestReser)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelPriceReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelNumOfGuestReser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelShowType))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPriceReservation)
                    .addComponent(jCheckBox1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelReservationNo.setText("jLabel10");

        jButton3.setText("Continue");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelReservationNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabelReservationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPaneReservationLayout = new javax.swing.GroupLayout(jLayeredPaneReservation);
        jLayeredPaneReservation.setLayout(jLayeredPaneReservationLayout);
        jLayeredPaneReservationLayout.setHorizontalGroup(
            jLayeredPaneReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneReservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPaneReservationLayout.setVerticalGroup(
            jLayeredPaneReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneReservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneReservation.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPaneReservationInfo.setMinimumSize(new java.awt.Dimension(625, 380));

        jButtonSeachReservationNo.setText("Search");
        jButtonSeachReservationNo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSeachReservationNoActionPerformed(evt);
            }
        });

        jTextFieldReservationInfoSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldReservationInfoSearchActionPerformed(evt);
            }
        });

        jLabel10.setText("Reservation No");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldReservationInfoSearch)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldReservationInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextAreaReservationInfo.setColumns(20);
        jTextAreaReservationInfo.setRows(5);
        jScrollPane13.setViewportView(jTextAreaReservationInfo);

        javax.swing.GroupLayout jLayeredPaneReservationInfoLayout = new javax.swing.GroupLayout(jLayeredPaneReservationInfo);
        jLayeredPaneReservationInfo.setLayout(jLayeredPaneReservationInfoLayout);
        jLayeredPaneReservationInfoLayout.setHorizontalGroup(
            jLayeredPaneReservationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneReservationInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneReservationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPaneReservationInfoLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSeachReservationNo))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneReservationInfoLayout.setVerticalGroup(
            jLayeredPaneReservationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneReservationInfoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jLayeredPaneReservationInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSeachReservationNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneReservationInfo.setLayer(jButtonSeachReservationNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneReservationInfo.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneReservationInfo.setLayer(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPaneSearchGuest.setMinimumSize(new java.awt.Dimension(625, 380));

        jButton4.setText("jButton4");

        jTextField2.setText("jTextField2");

        jLabel11.setText("Reservaton No");

        jLabel12.setText("Guest No");

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        jList2.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout jLayeredPaneSearchGuestLayout = new javax.swing.GroupLayout(jLayeredPaneSearchGuest);
        jLayeredPaneSearchGuest.setLayout(jLayeredPaneSearchGuestLayout);
        jLayeredPaneSearchGuestLayout.setHorizontalGroup(
            jLayeredPaneSearchGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSearchGuestLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jLayeredPaneSearchGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneSearchGuestLayout.setVerticalGroup(
            jLayeredPaneSearchGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSearchGuestLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneSearchGuest.setLayer(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSearchGuest.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fName.setText("First Name");

        lName.setText("Last Name");

        Address.setText("Address");

        country.setText("Country");

        phoneNo.setText("Phone");

        email.setText("E-mail");

        trvlAgncy.setText("Travel agency");

        checkin.setText("Check-in date");

        noOfnights.setText("No. of nights");

        jScrollPane4.setViewportView(fNamePANE);

        jScrollPane5.setViewportView(lNamePANE);

        jScrollPane6.setViewportView(AddressPANE);

        jScrollPane7.setViewportView(countryPANE);

        jScrollPane8.setViewportView(phoneNoPANE);

        jScrollPane9.setViewportView(emailPANE);

        jScrollPane10.setViewportView(trvlAgncyPANE);

        jScrollPane11.setViewportView(checkinPANE);

        jScrollPane12.setViewportView(noOfnightsPANE);

        guestInfoSaveButton.setText("Save");
        guestInfoSaveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guestInfoSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPaneEnterGuestInfoLayout = new javax.swing.GroupLayout(jLayeredPaneEnterGuestInfo);
        jLayeredPaneEnterGuestInfo.setLayout(jLayeredPaneEnterGuestInfoLayout);
        jLayeredPaneEnterGuestInfoLayout.setHorizontalGroup(
            jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneEnterGuestInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPaneEnterGuestInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guestInfoSaveButton))
                    .addGroup(jLayeredPaneEnterGuestInfoLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fName)
                            .addComponent(noOfnights)
                            .addComponent(checkin)
                            .addComponent(trvlAgncy)
                            .addComponent(email)
                            .addComponent(phoneNo)
                            .addComponent(country)
                            .addComponent(Address)
                            .addComponent(lName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jLayeredPaneEnterGuestInfoLayout.setVerticalGroup(
            jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneEnterGuestInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fName)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lName)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(country)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNo)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trvlAgncy)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkin)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneEnterGuestInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noOfnights)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guestInfoSaveButton)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jLayeredPaneEnterGuestInfo.setLayer(fName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(lName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(Address, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(country, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(phoneNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(trvlAgncy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(checkin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(noOfnights, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneEnterGuestInfo.setLayer(guestInfoSaveButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jListOverDue.setForeground(new java.awt.Color(255, 51, 51));
        jListOverDue.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListOverDue);

        jButtonFindOpenReservations.setText("Refresh");
        jButtonFindOpenReservations.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonFindOpenReservationsActionPerformed(evt);
            }
        });

        jListOpen.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListOpen.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jListOpenMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(jListOpen);

        jLabel13.setText("Open Bookings");

        jLabel14.setText("OverDue reservations");

        javax.swing.GroupLayout jLayeredPaneShowOpenReservationsLayout = new javax.swing.GroupLayout(jLayeredPaneShowOpenReservations);
        jLayeredPaneShowOpenReservations.setLayout(jLayeredPaneShowOpenReservationsLayout);
        jLayeredPaneShowOpenReservationsLayout.setHorizontalGroup(
            jLayeredPaneShowOpenReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneShowOpenReservationsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jLayeredPaneShowOpenReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addGroup(jLayeredPaneShowOpenReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonFindOpenReservations)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(jScrollPane14)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jLayeredPaneShowOpenReservationsLayout.setVerticalGroup(
            jLayeredPaneShowOpenReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneShowOpenReservationsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonFindOpenReservations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jLayeredPaneShowOpenReservations.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneShowOpenReservations.setLayer(jButtonFindOpenReservations, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneShowOpenReservations.setLayer(jScrollPane14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneShowOpenReservations.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneShowOpenReservations.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu2.setText("Search");

        jMenuItem1.setText("Search Reservation No");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Search for Room");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Search Guest");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Enter Guest Details");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Show Open Reservations");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar.add(jMenu2);

        jMenu1.setText("File");

        jMenuItemLogOut.setText("Log out");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogOut);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPaneSearchRoome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLayeredPaneReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 131, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPaneReservationInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPaneSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPaneEnterGuestInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(324, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(jLayeredPaneShowOpenReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPaneSearchRoome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLayeredPaneReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 91, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPaneReservationInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 46, Short.MAX_VALUE)
                    .addComponent(jLayeredPaneSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 45, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPaneEnterGuestInfo)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLayeredPaneShowOpenReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxTypeActionPerformed
    {//GEN-HEADEREND:event_jComboBoxTypeActionPerformed

        priceType = priceList[jComboBoxType.getSelectedIndex()];

        jLabelShowPrice.setText(Integer.toString(priceType));
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        model.clear();
        jList1.setModel(model);
        boolean getrooms = false;
        ArrayList<Room> arrayForJlist = null;

        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yy");
        Calendar c = Calendar.getInstance();
        startDate = null;
        endDate = null;
        bookingDate = c.getTime();
        int numberOfDays = Integer.parseInt(jTextFieldNumberOfDays.getText());

        if (jTextFieldStartDate.getDate().before(jTextFieldStartDate.getMinSelectableDate()))
        {
            startDate = null;
            JOptionPane.showMessageDialog(null, "unavailable date", "Invalid date", JOptionPane.OK_OPTION);
        }
        else
        {
            startDate = (jTextFieldStartDate.getDate());
        }
        startDateStr = dateFormat.format(startDate);

        c.setTime(startDate);
        c.add(Calendar.DATE, numberOfDays);
        endDate = c.getTime();
        endDateStr = dateFormat.format(endDate); //changed here c.getTime()
        jLabelEndDate.setText(endDateStr);

        numOfGuest = Integer.parseInt(jTextField1.getText());

        if (jComboBoxType.getSelectedIndex() == 0 && numOfGuest == 1)
        {
            type = "single";
            jLabelTypeShow.setText(type);
            getrooms = true;
        }
        else if (jComboBoxType.getSelectedIndex() == 0 && numOfGuest > 1)
        {
            jLabelTypeShow.setText("Too many guests!");
        }

        if (jComboBoxType.getSelectedIndex() == 1 && numOfGuest <= 2)
        {
            type = "double";
            jLabelTypeShow.setText(type);
            getrooms = true;
        }
        else if (numOfGuest > 2)
        {
            jLabelTypeShow.setText("Too many guests!");
        }

        if (jComboBoxType.getSelectedIndex() == 2 && numOfGuest <= 5)
        {
            type = "family";
            jLabelTypeShow.setText(type);
            getrooms = true;
        }
        else if (numOfGuest > 5)
        {
            jLabelTypeShow.setText("Too many guests!");
        }
        if (numberOfDays == 0)
        {
            getrooms = false;
            jLabelTypeShow.setText("");
        }

        if (getrooms)
        {
            arrayForJlist = control.getRoomsAvailable(startDate, endDate, type);
            totalPriceForRoom = priceType * numberOfDays;
            jLabelShowTotalPrice.setText(Integer.toString(totalPriceForRoom));
        }
        if (arrayForJlist == null)
        {
            model.addElement("No Room available");
            jLabelShowTotalPrice.setText("");
            JOptionPane.showMessageDialog(null, "No room available", "", JOptionPane.OK_OPTION);
        }
        else
        {
            for (Room r : arrayForJlist)
            {
                System.out.println(r.getRoomNo());
                model.addElement(r.getRoomNo());
            }

        }

        jList1.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNumberOfDaysActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldNumberOfDaysActionPerformed
    {//GEN-HEADEREND:event_jTextFieldNumberOfDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumberOfDaysActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed

        depositPaid = 0;
        int jListSelectedIndex = jList1.getSelectedIndex();
        Object roomNoSelected = model.getElementAt(jListSelectedIndex);
        roomNo = Integer.parseInt(roomNoSelected.toString());
        jLabelShowRoomChosen.setText(roomNoSelected.toString());

        currentPane.setVisible(false);
        jLabelSelectedStartDate.setText(startDateStr); // could be dateFormat.format(startDate) perhabs
        jLabelToDate.setText(endDateStr);
        jLabelNumOfGuestReser.setText(Integer.toString(numOfGuest));
        jLabelShowType.setText(type);
        jLabelPriceReservation.setText(Integer.toString(totalPriceForRoom));
        reservationNo = control.getNextReservationNo();
        jLabelReservationNo.setText(Integer.toString(reservationNo));

        currentPane = jLayeredPaneReservation;

        currentPane.setVisible(true);

        boolean result = control.bookRoom(roomNo, reservationNo, startDate, endDate, bookingDate, depositPaid);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
//        if (jCheckBox1.isSelected())
//        {
//            depositPaid = 1;
//        }
//
//        control.bookRoom(roomNo, reservationNo, startDate, endDate, bookingDate, depositPaid);
        currentPane.setVisible(false);
        currentPane = jLayeredPaneEnterGuestInfo;
        currentPane.setVisible(true);
        fNamePANE.setText("");
        lNamePANE.setText("");
        checkinPANE.setText(startDateStr);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBox1ActionPerformed
    {//GEN-HEADEREND:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        currentPane.setVisible(false);
        currentPane = jLayeredPaneReservationInfo;
        currentPane.setVisible(true);
        CasablancaResception.this.setPreferredSize(new Dimension(290, 400));
        CasablancaResception.this.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextFieldReservationInfoSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldReservationInfoSearchActionPerformed
    {//GEN-HEADEREND:event_jTextFieldReservationInfoSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReservationInfoSearchActionPerformed

    private void jButtonSeachReservationNoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSeachReservationNoActionPerformed
    {//GEN-HEADEREND:event_jButtonSeachReservationNoActionPerformed
        String reservation = control.getReservationDetails(Integer.parseInt(jTextFieldReservationInfoSearch.getText()));
        jTextAreaReservationInfo.setText(reservation);
    }//GEN-LAST:event_jButtonSeachReservationNoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        currentPane.setVisible(false);
        currentPane = jLayeredPaneSearchRoome;
        currentPane.setVisible(true);
        CasablancaResception.this.setPreferredSize(new Dimension(575, 400));
        CasablancaResception.this.pack();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem3ActionPerformed
        currentPane.setVisible(false);
        currentPane = jLayeredPaneSearchGuest;
        currentPane.setVisible(true);
        CasablancaResception.this.setPreferredSize(new Dimension(260, 440));
        CasablancaResception.this.pack();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void guestInfoSaveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guestInfoSaveButtonActionPerformed
    {//GEN-HEADEREND:event_guestInfoSaveButtonActionPerformed
        // TODO add your handling code here:
        Random ran = new Random();
        String guestNo = String.valueOf(reservationNo) + "-" + (guestcounter + 1);
        System.out.println(guestNo);
        int password = ran.nextInt(9000) + 1000;

        control.createGuest(reservationNo, guestNo, password, fNamePANE.getText(), lNamePANE.getText(),
                AddressPANE.getText(), countryPANE.getText(), Integer.parseInt(phoneNoPANE.getText()), emailPANE.getText(), trvlAgncyPANE.getText());

        control.commit();
        guestcounter++;

        if (guestcounter < numOfGuest)
        {
            jButton3ActionPerformed(evt);
        }
        else
        {

            guestcounter = 0;
            currentPane.setVisible(false);
            currentPane = jLayeredPaneSearchRoome;
            currentPane.setVisible(true);
//            try
//            { String email= control.getGuests(reservationNo).get(0).getEmail();
//              control.sendInvoice(email, control.getReservation(reservationNo), control.getGuests(reservationNo), type, priceType);
//            }
//            catch (MessagingException ex)
//            {System.out.println("Messege sending failed");
//                Logger.getLogger(CasablancaResception.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }


    }//GEN-LAST:event_guestInfoSaveButtonActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        currentPane.setVisible(false);
        currentPane = jLayeredPaneEnterGuestInfo;
        currentPane.setVisible(true);
        CasablancaResception.this.setPreferredSize(new Dimension(350, 570));
        CasablancaResception.this.pack();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(null, "Do you want to close?", "", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemLogOutActionPerformed
    {//GEN-HEADEREND:event_jMenuItemLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem5ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem5ActionPerformed
        currentPane.setVisible(false);
        currentPane = jLayeredPaneShowOpenReservations;
        jLayeredPaneShowOpenReservations.setVisible(true);
        getOpenReservations();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButtonFindOpenReservationsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonFindOpenReservationsActionPerformed
    {//GEN-HEADEREND:event_jButtonFindOpenReservationsActionPerformed
        overDueDeposit.clear();
        showOpenReservation.clear();
        getOpenReservations();
    }//GEN-LAST:event_jButtonFindOpenReservationsActionPerformed

    private void jListOpenMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jListOpenMouseClicked
    {//GEN-HEADEREND:event_jListOpenMouseClicked

        if (evt.getClickCount() == 2)
        {
            System.out.println("double clicked , congrats, it works");
            int index = jListOpen.locationToIndex(evt.getPoint());
            int reservationNoSelected = (Integer) overDueDeposit.get(index);
            boolean haveCurrentReservation = control.getCurrentReservation(reservationNoSelected);
            System.out.println("status of currentReservation " + haveCurrentReservation);

            if (haveCurrentReservation)
            {
                int choice = JOptionPane.showConfirmDialog(null, "Has the deposit been paid?", "", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION)
                {
                    boolean result = control.updateDeposit();
                    if (result)
                    {

                        control.commit();;
                        JOptionPane.showMessageDialog(null, "Deposit paid\nfor reservation: " + reservationNoSelected, "Deposit paid", 1);
                        overDueDeposit.clear();
                        showOpenReservation.clear();
                        getOpenReservations();

                        Reservation res = control.getReservation(reservationNoSelected);
                        ArrayList<Guest> guestarray = control.getGuests(reservationNoSelected);
                        System.out.println("guestarray got");
                       System.out.println(guestarray.size());
                        String email = guestarray.get(0).getEmail();
                        System.out.println("email got" + email);
                        String roomType = control.getRoomType(res.getRoomNo());
                        System.out.println("roomtype got");
                        try
                        {
                            control.sendConfirmation(email, res, guestarray, roomType);
                        }
                        catch (MessagingException ex)
                        {
                            System.out.println("Messege sending failed");
                            Logger.getLogger(CasablancaResception.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_jListOpenMouseClicked

    private void jButtonPrintDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonPrintDateActionPerformed
    {//GEN-HEADEREND:event_jButtonPrintDateActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yy");
        Date dateFromChooser = jTextFieldStartDate.getDate();
        System.out.println(sdf.format(dateFromChooser));
    }//GEN-LAST:event_jButtonPrintDateActionPerformed

    private void jTextFieldStartDateFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTextFieldStartDateFocusLost
    {//GEN-HEADEREND:event_jTextFieldStartDateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStartDateFocusLost
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaResception.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaResception.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaResception.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CasablancaResception.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CasablancaResception().setVisible(true);
            }
        });
    }

    public void getOpenReservations()
    {

        ArrayList<Reservation> res = new ArrayList<>(control.getReservationDepositNotPaid());
        Calendar c = Calendar.getInstance();
        Date today = c.getTime(); //Booking date could be change to today in booking for keeping variable down;
        if (res == null)
        {
            showOpenReservation.addElement("All paid");
        }
        else
        {
            for (Reservation reservation : res)
            {
                c.setTime((reservation.getBoookingDate()));
                c.add(Calendar.DATE, 5);
                if ((today.after(c.getTime())))
                {
                    showOpenReservation.addElement(reservation.getReservationNo());
                }
                else
                {
                    overDueDeposit.addElement(reservation.getReservationNo());
                }
            }
        }

        jListOverDue.setModel(showOpenReservation);
        jListOpen.setModel(overDueDeposit);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextPane AddressPANE;
    private javax.swing.JLabel checkin;
    private javax.swing.JTextPane checkinPANE;
    private javax.swing.JLabel country;
    private javax.swing.JTextPane countryPANE;
    private javax.swing.JLabel email;
    private javax.swing.JTextPane emailPANE;
    private javax.swing.JLabel fName;
    private javax.swing.JTextPane fNamePANE;
    private javax.swing.JButton guestInfoSaveButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonFindOpenReservations;
    private javax.swing.JButton jButtonPrintDate;
    private javax.swing.JButton jButtonSeachReservationNo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEndDate;
    private javax.swing.JLabel jLabelNumOfGuestReser;
    private javax.swing.JLabel jLabelPriceReservation;
    private javax.swing.JLabel jLabelReservationNo;
    private javax.swing.JLabel jLabelSelectedStartDate;
    private javax.swing.JLabel jLabelShowPrice;
    private javax.swing.JLabel jLabelShowRoomChosen;
    private javax.swing.JLabel jLabelShowTotalPrice;
    private javax.swing.JLabel jLabelShowType;
    private javax.swing.JLabel jLabelToDate;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelTypeShow;
    private javax.swing.JLayeredPane jLayeredPaneEnterGuestInfo;
    private javax.swing.JLayeredPane jLayeredPaneReservation;
    private javax.swing.JLayeredPane jLayeredPaneReservationInfo;
    private javax.swing.JLayeredPane jLayeredPaneSearchGuest;
    private javax.swing.JLayeredPane jLayeredPaneSearchRoome;
    private javax.swing.JLayeredPane jLayeredPaneShowOpenReservations;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jListOpen;
    private javax.swing.JList jListOverDue;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextAreaReservationInfo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldNumberOfDays;
    private javax.swing.JTextField jTextFieldReservationInfoSearch;
    private com.toedter.calendar.JDateChooser jTextFieldStartDate;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lName;
    private javax.swing.JTextPane lNamePANE;
    private javax.swing.JLabel noOfnights;
    private javax.swing.JTextPane noOfnightsPANE;
    private javax.swing.JLabel phoneNo;
    private javax.swing.JTextPane phoneNoPANE;
    private javax.swing.JLabel trvlAgncy;
    private javax.swing.JTextPane trvlAgncyPANE;
    // End of variables declaration//GEN-END:variables
}
